
#	Source files
#
SOURCES		=	main.c	\
			swuart.sx

CONFIG		=	HW_DEVICE			\
			hw_syshz			\
			HW_SWUART0_PIN_RX		\
			HW_SWUART0_PIN_TX		\
			HW_SWUART0_AUTOSYNC		\
			HW_SWUART0_COUNTER		\
			HW_SWUART0_COUNTER_CLK_DIV	\
			HW_SWUART0_COUNTER_COMP

include ../make/Makefile
