
#	Source files
#
SOURCES		=	main.c

CONFIG		=	HW_DEVICE		\
			hw_syshz		\
			PIN_LED			\
			INPUT_POS		\
			INPUT_NEG		\
			EDGE			\
			COUNTER			\
			COUNTER_CLK_DIV		\
			COMPARE			\
			PERIOD

include ../make/Makefile
