
#	Source files
#
SOURCES		=	main.c		\
			swuart.sx

#	Configuration memorized / checked
#
CONFIG		=	HW_DEVICE			\
			hw_syshz			\
			HW_SWUART0_PIN_RX		\
			HW_SWUART0_PIN_TX		\
			HW_SWUART0_COUNTER		\
			HW_SWUART0_COUNTER_CLK_DIV	\
			HW_SWUART0_COUNTER_COMP		\
			UART				\
			COUNTER				\
			CAPTURE				\
			COMPARE				\
			PIN_LED				\
			PIN_TCS3200_S2			\
			PIN_TCS3200_S3			\
			_PIN_OUTS			\
			PIN_OUT0			\
			PIN_OUT1			\
			PIN_OUT2			\
			PIN_OUT3


include ../../../../make/Makefile
