
#	Source files
#
SOURCES		=	main.c

CONFIG		=	HW_DEVICE			\
			hw_syshz			\
			hw_swuart0_pin_rxd		\
			hw_swuart0_pin_txd		\
			hw_swuart0_autosync		\
			hw_swuart0_compare		\
			hw_swuart0_clk_div		\
			UART				\
			USI				\
			NRF_CSN

BOARD		?= nanodccduino

include ../../Makefile
