
#	Source files
#
SOURCES		=	main.c

CONFIG		=	HW_DEVICE		\
			hw_syshz		\
			PIN_LED			\
			PWM_PERIOD		\
			PWM_TMIN		\
			PWM_TMAX		\
			COMPARE_MIN		\
			COMPARE_MAX		\
			INPUT			\
			COUNTER			\
			COUNTER_CLK_DIV		\
			ADC_CLK_DIV

include ../../../../make/Makefile
