#ifndef HWA_GPIO_PORTS_H
#define HWA_GPIO_PORTS_H

#define HW_SPLITPORT_PA0		PORTA, 0
#define HW_SPLITPORT_PA1		PORTA, 1
#define HW_SPLITPORT_PA2		PORTA, 2
#define HW_SPLITPORT_PA3		PORTA, 3
#define HW_SPLITPORT_PA4		PORTA, 4
#define HW_SPLITPORT_PA5		PORTA, 5
#define HW_SPLITPORT_PA6		PORTA, 6
#define HW_SPLITPORT_PA7		PORTA, 7
#define HW_SPLITPORT_PA8		PORTA, 8
#define HW_SPLITPORT_PA9		PORTA, 9
#define HW_SPLITPORT_PA10		PORTA, 10
#define HW_SPLITPORT_PA11		PORTA, 11
#define HW_SPLITPORT_PA12		PORTA, 12
#define HW_SPLITPORT_PA13		PORTA, 13
#define HW_SPLITPORT_PA14		PORTA, 14
#define HW_SPLITPORT_PA15		PORTA, 15

#define HW_SPLITPORT_PB0		PORTB, 0
#define HW_SPLITPORT_PB1		PORTB, 1
#define HW_SPLITPORT_PB2		PORTB, 2
#define HW_SPLITPORT_PB3		PORTB, 3
#define HW_SPLITPORT_PB4		PORTB, 4
#define HW_SPLITPORT_PB5		PORTB, 5
#define HW_SPLITPORT_PB6		PORTB, 6
#define HW_SPLITPORT_PB7		PORTB, 7
#define HW_SPLITPORT_PB8		PORTB, 8
#define HW_SPLITPORT_PB9		PORTB, 9
#define HW_SPLITPORT_PB10		PORTB, 10
#define HW_SPLITPORT_PB11		PORTB, 11
#define HW_SPLITPORT_PB12		PORTB, 12
#define HW_SPLITPORT_PB13		PORTB, 13
#define HW_SPLITPORT_PB14		PORTB, 14
#define HW_SPLITPORT_PB15		PORTB, 15

#define HW_SPLITPORT_PC0		PORTC, 0
#define HW_SPLITPORT_PC1		PORTC, 1
#define HW_SPLITPORT_PC2		PORTC, 2
#define HW_SPLITPORT_PC3		PORTC, 3
#define HW_SPLITPORT_PC4		PORTC, 4
#define HW_SPLITPORT_PC5		PORTC, 5
#define HW_SPLITPORT_PC6		PORTC, 6
#define HW_SPLITPORT_PC7		PORTC, 7
#define HW_SPLITPORT_PC8		PORTC, 8
#define HW_SPLITPORT_PC9		PORTC, 9
#define HW_SPLITPORT_PC10		PORTC, 10
#define HW_SPLITPORT_PC11		PORTC, 11
#define HW_SPLITPORT_PC12		PORTC, 12
#define HW_SPLITPORT_PC13		PORTC, 13
#define HW_SPLITPORT_PC14		PORTC, 14
#define HW_SPLITPORT_PC15		PORTC, 15

#define HW_SPLITPORT_PD0		PORTD, 0
#define HW_SPLITPORT_PD1		PORTD, 1
#define HW_SPLITPORT_PD2		PORTD, 2
#define HW_SPLITPORT_PD3		PORTD, 3
#define HW_SPLITPORT_PD4		PORTD, 4
#define HW_SPLITPORT_PD5		PORTD, 5
#define HW_SPLITPORT_PD6		PORTD, 6
#define HW_SPLITPORT_PD7		PORTD, 7
#define HW_SPLITPORT_PD8		PORTD, 8
#define HW_SPLITPORT_PD9		PORTD, 9
#define HW_SPLITPORT_PD10		PORTD, 10
#define HW_SPLITPORT_PD11		PORTD, 11
#define HW_SPLITPORT_PD12		PORTD, 12
#define HW_SPLITPORT_PD13		PORTD, 13
#define HW_SPLITPORT_PD14		PORTD, 14
#define HW_SPLITPORT_PD15		PORTD, 15

#define HW_SPLITPORT_PE0		PORTE, 0
#define HW_SPLITPORT_PE1		PORTE, 1
#define HW_SPLITPORT_PE2		PORTE, 2
#define HW_SPLITPORT_PE3		PORTE, 3
#define HW_SPLITPORT_PE4		PORTE, 4
#define HW_SPLITPORT_PE5		PORTE, 5
#define HW_SPLITPORT_PE6		PORTE, 6
#define HW_SPLITPORT_PE7		PORTE, 7
#define HW_SPLITPORT_PE8		PORTE, 8
#define HW_SPLITPORT_PE9		PORTE, 9
#define HW_SPLITPORT_PE10		PORTE, 10
#define HW_SPLITPORT_PE11		PORTE, 11
#define HW_SPLITPORT_PE12		PORTE, 12
#define HW_SPLITPORT_PE13		PORTE, 13
#define HW_SPLITPORT_PE14		PORTE, 14
#define HW_SPLITPORT_PE15		PORTE, 15

#define _HW_SPLITPORT(p)	HW_SPLITPORT_##p
#define HW_SPLITPORT(p)		_HW_SPLITPORT(p)

#define __HW_PORTNAME(sp)	HWA_1of2(sp)
#define _HW_PORTNAME(p)		__HW_PORTNAME(HW_SPLITPORT(p))
#define HW_PORTNAME(p)		_HW_PORTNAME(p)

#define __HW_PINNUM(sp)		HWA_2of2(sp)
#define _HW_PINNUM(p)		__HW_PINNUM(HW_SPLITPORT(p))
#define HW_PINNUM(p)		_HW_PINNUM(p)

#endif
