#ifndef HWA_TIMER_H
#define HWA_TIMER_H

#define HWA_TIMER_MODE_LOOP_UP		1
#define HWA_TIMER_MODE_X		2

#define HWA_TIMER_CLK_SYSCLK_PSC	0b00	/* default */
#define HWA_TIMER_CLK_TOSC_PSC		0b01
#define HWA_TIMER_CLK_EXTERN		0b11

#define HWA_TIMER_DIR_COUNT_UP		0
#define HWA_TIMER_DIR_COUNT_DOWN	1

#endif
