#ifndef HWA_GPIO_PINS_H
#define HWA_GPIO_PINS_H

#define HWA_PIN_PA0			HWA_PORTA, 0
#define HWA_PIN_PA1			HWA_PORTA, 1
#define HWA_PIN_PA2			HWA_PORTA, 2
#define HWA_PIN_PA3			HWA_PORTA, 3
#define HWA_PIN_PA4			HWA_PORTA, 4
#define HWA_PIN_PA5			HWA_PORTA, 5
#define HWA_PIN_PA6			HWA_PORTA, 6
#define HWA_PIN_PA7			HWA_PORTA, 7
#define HWA_PIN_PA8			HWA_PORTA, 8
#define HWA_PIN_PA9			HWA_PORTA, 9
#define HWA_PIN_PA10		HWA_PORTA, 10
#define HWA_PIN_PA11		HWA_PORTA, 11
#define HWA_PIN_PA12		HWA_PORTA, 12
#define HWA_PIN_PA13		HWA_PORTA, 13
#define HWA_PIN_PA14		HWA_PORTA, 14
#define HWA_PIN_PA15		HWA_PORTA, 15

#define HWA_PIN_PB0			HWA_PORTB, 0
#define HWA_PIN_PB1			HWA_PORTB, 1
#define HWA_PIN_PB2			HWA_PORTB, 2
#define HWA_PIN_PB3			HWA_PORTB, 3
#define HWA_PIN_PB4			HWA_PORTB, 4
#define HWA_PIN_PB5			HWA_PORTB, 5
#define HWA_PIN_PB6			HWA_PORTB, 6
#define HWA_PIN_PB7			HWA_PORTB, 7
#define HWA_PIN_PB8			HWA_PORTB, 8
#define HWA_PIN_PB9			HWA_PORTB, 9
#define HWA_PIN_PB10		HWA_PORTB, 10
#define HWA_PIN_PB11		HWA_PORTB, 11
#define HWA_PIN_PB12		HWA_PORTB, 12
#define HWA_PIN_PB13		HWA_PORTB, 13
#define HWA_PIN_PB14		HWA_PORTB, 14
#define HWA_PIN_PB15		HWA_PORTB, 15

#define HWA_PIN_PC0			HWA_PORTC, 0
#define HWA_PIN_PC1			HWA_PORTC, 1
#define HWA_PIN_PC2			HWA_PORTC, 2
#define HWA_PIN_PC3			HWA_PORTC, 3
#define HWA_PIN_PC4			HWA_PORTC, 4
#define HWA_PIN_PC5			HWA_PORTC, 5
#define HWA_PIN_PC6			HWA_PORTC, 6
#define HWA_PIN_PC7			HWA_PORTC, 7
#define HWA_PIN_PC8			HWA_PORTC, 8
#define HWA_PIN_PC9			HWA_PORTC, 9
#define HWA_PIN_PC10		HWA_PORTC, 10
#define HWA_PIN_PC11		HWA_PORTC, 11
#define HWA_PIN_PC12		HWA_PORTC, 12
#define HWA_PIN_PC13		HWA_PORTC, 13
#define HWA_PIN_PC14		HWA_PORTC, 14
#define HWA_PIN_PC15		HWA_PORTC, 15

#define HWA_PIN_PD0			HWA_PORTD, 0
#define HWA_PIN_PD1			HWA_PORTD, 1
#define HWA_PIN_PD2			HWA_PORTD, 2
#define HWA_PIN_PD3			HWA_PORTD, 3
#define HWA_PIN_PD4			HWA_PORTD, 4
#define HWA_PIN_PD5			HWA_PORTD, 5
#define HWA_PIN_PD6			HWA_PORTD, 6
#define HWA_PIN_PD7			HWA_PORTD, 7
#define HWA_PIN_PD8			HWA_PORTD, 8
#define HWA_PIN_PD9			HWA_PORTD, 9
#define HWA_PIN_PD10		HWA_PORTD, 10
#define HWA_PIN_PD11		HWA_PORTD, 11
#define HWA_PIN_PD12		HWA_PORTD, 12
#define HWA_PIN_PD13		HWA_PORTD, 13
#define HWA_PIN_PD14		HWA_PORTD, 14
#define HWA_PIN_PD15		HWA_PORTD, 15

#define HWA_PIN_PE0			HWA_PORTE, 0
#define HWA_PIN_PE1			HWA_PORTE, 1
#define HWA_PIN_PE2			HWA_PORTE, 2
#define HWA_PIN_PE3			HWA_PORTE, 3
#define HWA_PIN_PE4			HWA_PORTE, 4
#define HWA_PIN_PE5			HWA_PORTE, 5
#define HWA_PIN_PE6			HWA_PORTE, 6
#define HWA_PIN_PE7			HWA_PORTE, 7
#define HWA_PIN_PE8			HWA_PORTE, 8
#define HWA_PIN_PE9			HWA_PORTE, 9
#define HWA_PIN_PE10		HWA_PORTE, 10
#define HWA_PIN_PE11		HWA_PORTE, 11
#define HWA_PIN_PE12		HWA_PORTE, 12
#define HWA_PIN_PE13		HWA_PORTE, 13
#define HWA_PIN_PE14		HWA_PORTE, 14
#define HWA_PIN_PE15		HWA_PORTE, 15

#define HWA_PIN(p)			_HWA_PIN(p)
#define _HWA_PIN(p)			HWA_PIN_##p

#define HWA_PORTNAME(p)			_HWA_PORTNAME(p)
#define _HWA_PORTNAME(p)		__HWA_PORTNAME(HWA_PIN(p))
#define __HWA_PORTNAME(p)		HWA_1ST(p)

#define HWA_PINNUM(p)			_HWA_PINNUM(p)
#define _HWA_PINNUM(p)			__HWA_PINNUM(HWA_PIN(p))
#define __HWA_PINNUM(p)			HWA_2ND(p)

#endif
