
BOARD		?=	nanodccduino

#	Source files
#
SOURCES		=	main.c xprintf.c

#	Configuration memorized / checked
#
CONFIG		=	HW_DEVICE			\
			HW_SYSHZ			\
			TWI				\
			TWI_BPS				\
			LCD				\
			PCF


include ../make/Makefile
