
#	-*- Makefile -*-

#$(warning Makefile.attiny85)

AVRDUDE_PARTNO		= t85

# PROG_SW			?= diabolo

DIABOLO_BPS		= 230400
DIABOLO_KEEP_TXD_LOW	= 0.129		# 30 ms more than computed value
DIABOLO_RESET_SIGNAL	= DTR
