
#	-*- Makefile -*-

#  The pro-micro Arduino clone board is preloaded with the Caterina AVR109
#  compatible bootloader that is supported by Avrdude.

# PROG_HW		?= avr109
# PROG_SW		?= avrdude

DIABOLO_BPS		= 230400
DIABOLO_RESET_SIGNAL	= DTR
DIABOLO_SYNC		= 5+1
