
BOARD		?=	attiny84-tcs3200

#	Source files
#
SOURCES		=	main.c		\
			swuart.sx

#	Configuration memorized / checked
#
CONFIG		=	HW_DEVICE			\
			hw_syshz			\
			hw_swuart0_pin_rxd		\
			hw_swuart0_pin_txd		\
			hw_swuart0_autosync		\
			hw_swuart0_compare		\
			hw_swuart0_clk_div		\
			UART				\
			COUNTER				\
			CAPTURE				\
			COMPARE				\
			PIN_LED				\
			PIN_TCS3200_S2			\
			PIN_TCS3200_S3			\
			PIN_OUTS			\
			PIN_OUT0			\
			PIN_OUT1			\
			PIN_OUT2			\
			PIN_OUT3

include ../Makefile
