
#	Source files
#
SOURCES		=	main.c		\
			swuart.sx

#	Configuration memorized / checked
#
CONFIG		=	HW_DEVICE			\
			hw_syshz			\
			hw_swuart0_pin_rx		\
			hw_swuart0_pin_tx		\
			hw_swuart0_counter		\
			hw_swuart0_counter_clk_div	\
			hw_swuart0_counter_compare	\
			UART				\
			COUNTER				\
			CAPTURE				\
			COMPARE				\
			PIN_LED				\
			PIN_TCS3200_S2			\
			PIN_TCS3200_S3			\
			_PIN_OUTS			\
			PIN_OUT0			\
			PIN_OUT1			\
			PIN_OUT2			\
			PIN_OUT3


include ../../../../make/Makefile
