#	-*- makefile -*-

PATH:=$(CWD)../../tools/diabolo/software:$(PATH)

erase:
	diabolo.py $(DIABOLO_OPTS)	\
		--erase-flash

burn:	$(OBJDIR)/$(OUT).bin
	diabolo.py $(DIABOLO_OPTS)	\
		--flash-file $^

diabolo:
	diabolo.py $(DIABOLO_OPTS)

.PHONY: crc
crc:	$(OBJDIR)/$(OUT).bin
	diabolo.py -c $(OBJDIR)/$(OUT).bin
