

$(ROM_LD): Makefile tools/rom.ld.in
	@mkdir -p $(dir $@)
	@cat tools/rom.ld.in | sed -e 's/ROM_ORG/${ROM_ORG}/g' >$@


$(RAM_LD): Makefile tools/ram.ld.in
	@mkdir -p $(dir $@)
	@cat tools/ram.ld.in >$@
