
#	-*- makefile -*-

PARTNO	=	m48
FLASHSZ	=	0x1000

#  Fuse Extended Byte (0x01)
#
#			1111
#			111
#	SELFPRGEN	0	0  Self programming enabled
#				1  Self programming disabled
#
FUSE_EB	=	0xFE

include make/Makefile.atmegaX8
