
#	-*- makefile -*-

PARTNO	=	m88
FLASHSZ	=	0x2000

#  Fuse Extended Byte (0xF9)
#
#			1111 1	----
#	BOOTSZ1:0	00	00 1024 words bootloader
#				01  512 words bootloader
#				10  256 words bootloader
#				11  128 words bootloader
#	BOOTRST			0  Reset -> bootloader
#			1	1  Reset -> 0x000
#
EFUSE	=	0x01

include make/Makefile.atmegaX8
