
#	Source files
#
SOURCES		=	main.c	\
			swuart.sx

CONFIG		=	HW_DEVICE			\
			hw_syshz			\
			hw_swuart0_pin_rx		\
			hw_swuart0_pin_tx		\
			hw_swuart0_counter		\
			hw_swuart0_counter_clk_div	\
			hw_swuart0_counter_compare	\
			UART				\
			SPI				\
			NRF_CSN

include ../../../../make/Makefile
