
#	Source files
#
SOURCES		=	main.c	\
			swuart.sx

CONFIG		=	HW_DEVICE			\
			hw_syshz			\
			UART				\
			BPS				\
			hw_swuart0_pin_txd		\
			hw_swuart0_compare		\
			hw_swuart0_clk_div

include ../Makefile
