
#	Source files
#
SOURCES		=	main.c

CONFIG		=	HW_DEVICE		\
			HW_SYSHZ		\
			PIN_LED			\
			REFERENCE		\
			PIN_ANALOG_INPUT	\
			EDGE			\
			COUNTER			\
			COUNTER_CLK_DIV		\
			COMPARE			\
			ON_TIME

include ../make/Makefile
